name: fer-monitorconfig
base: core22
version: '1.0.8'
summary: Control para brillo multiples monitores.
description: |
  Control para brillo multiples monitores.

grade: stable
confinement: strict

apps:
  fer-monitorconfig:
    command: Fer.MonitorConfig
    extensions:
      - gnome
    plugs:
      - home
      - network
      - x11

parts:
  fer-monitorconfig:
    plugin: dump
    source: ./bin/Release/net8.0/linux-x64/publish
    build-packages:
      - libgdk-pixbuf2.0-dev
    organize:
      bin/Release/net8.0/linux-x64/publish: bin
      meta/gui/Fer.MonitorConfig.desktop: desktop/Fer.MonitorConfig.desktop